### PR TITLE
[hubot_systemd]

### PR DESCRIPTION
**Pull request by khdevel**
- code for systemd in RedHat7/Centos7
- some syntax corrections and sorting
- changes should not affect on Ubuntu OS (was not tested)
- please review and test

Changes to be committed:
-	modified:   manifests/config.pp
-	modified:   manifests/init.pp
-	modified:   manifests/install.pp
-	modified:   manifests/params.pp
-	modified:   templates/hubot.env.erb
-	new file:   templates/hubot.systemd.erb

### CODE REVIEW

**Review by frozenfoxx — APPROVED** [review]
Looks great, thank you for the hard work!

**Comment by frozenfoxx** [comment]
Will create a new release to upload to the Forge very soon.

**Comment by khdevel** [comment]
Thank you very much but did you review it and test? On my Centos7 it works great but I would like to have the second pair of eyes to look on it ;)
Btw... I forgot to include rspec tests :/

**Comment by frozenfoxx** [comment]
At this time the rspec tests are likely outdated and I don't know enough to fix them.  It seems fine to me, if it fails I'll fix it or accept fixes from anyone else it broke for.  I reviewed your changes and they definitely look like they would not break anything.

**Pull request merged**
